name: ROBOT Build

on:
  workflow_dispatch:

jobs:
  robot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install ROBOT
        run: |
          curl -L -o robot.jar https://github.com/ontodev/robot/releases/download/v1.9.7/robot.jar
          echo '#!/usr/bin/env bash' > robot
          echo 'exec java -Xmx4G -jar $(dirname $0)/robot.jar "$@"' >> robot
          chmod +x robot
          echo "$(pwd)" >> $GITHUB_PATH
      - name: Build imports and artifacts
        run: |
          make ROBOT=robot imports convert report
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pcdo-artifacts
          path: |
            imports/*.owl
            dist/*
            reports/*

